CREATE TABLE CLIENT (
    ID_CLIENT BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(120),
    CPF VARCHAR(11) NOT NULL,
    REGISTRATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_CPF_CLIENT UNIQUE (CPF)
);

CREATE TABLE ORDERS (
    ID_ORDER BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENT BIGINT NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(30) NOT NULL,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    CONSTRAINT FK_ORDERS_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

CREATE TABLE PRODUCT (
    ID_PRODUCT BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(60) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    AMOUNT INT NOT NULL,
    CONSTRAINT UQ_NAME_PRODUCT UNIQUE (NAME)
);

CREATE TABLE PRODUCT_ORDERS (
    ID_PRODUCT BIGINT NOT NULL,
    ID_ORDERS BIGINT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    DISCOUNT DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ID_PRODUCT, ID_ORDERS),
    CONSTRAINT FK_ORDER_ITEMS_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT),
    CONSTRAINT FK_ORDER_ITEMS_ORDERS FOREIGN KEY (ID_ORDERS) REFERENCES ORDERS(ID_ORDERS)
);

INSERT INTO CLIENT (NAME, EMAIL, CPF) VALUES 
    ('Ana Silva', 'ana.silva@email.com', '12345678901'),
    ('Bruno Souza', 'bruno.souza@email.com', '98765432100'),
    ('Carla Dias', 'carla.dias@email.com', '45678912344');

INSERT INTO PRODUCT (NAME, PRICE, AMOUNT) VALUES 
    ('Notebook Gamer', 4500.00, 10),
    ('Mouse Sem Fio', 120.50, 50),
    ('Teclado Mecânico', 350.00, 25),
    ('Monitor 27', 1200.00, 15);

INSERT INTO ORDERS (ID_CLIENT, STATUS, TOTAL_AMOUNT) VALUES 
    (1, 'Completed', 4620.50),
    (1, 'Pending', 350.00),
    (2, 'Completed', 1200.00);

INSERT INTO PRODUCT_ORDERS (ID_ORDERS, ID_PRODUCT, QUANTITY, UNIT_PRICE, DISCOUNT) VALUES 
    (1, 1, 1, 4500.00, 0.00),
    (1, 2, 1, 120.50, 0.00),
    (2, 3, 1, 350.00, 0.00),
    (3, 4, 1, 1200.00, 0.00);


SELECT 
    c.NAME AS client_name,
    o.ID_ORDERS AS order_id,
    o.ORDER_DATE AS order_date,
    o.STATUS AS order_status,
    p.NAME AS product_name,
    po.QUANTITY AS quantity,
    po.UNIT_PRICE AS unit_price,
    (po.QUANTITY * po.UNIT_PRICE) - po.DISCOUNT AS item_subtotal
FROM ORDERS o
JOIN CLIENT c ON o.ID_CLIENT = c.ID_CLIENT
JOIN PRODUCT_ORDERS po ON o.ID_ORDERS = po.ID_ORDERS
JOIN PRODUCT p ON po.ID_PRODUCT = p.ID_PRODUCT
ORDER BY o.ID_ORDERS;
